// Generated by https://quicktype.io

import { Movie } from "./movies-popular.interface";

export interface MarkAsFavoriteResponse {
    status_code:    number;
    status_message: string;
}

// Generated by https://quicktype.io

export class FavoriteDto {
    media_type: string;
    media_id:   number;
    favorite:   boolean;

    constructor (movie_id: number, fav: boolean) {
        this.media_type = 'movie';
        this.media_id = movie_id;
        this.favorite = fav;
    }
}

export interface GetFavoriteMoviesResponse {
    page:          number;
    results:       Movie[];
    total_pages:   number;
    total_results: number;
}
