// Generated by https://quicktype.io

export interface CreatedListsResponse {
    page:          number;
    results:       lista[];
    total_pages:   number;
    total_results: number;
}

export interface lista {
    description:    string;
    favorite_count: number;
    id:             number;
    item_count:     number;
    iso_639_1:      string;
    list_type:      string;
    name:           string;
    poster_path:    null;
}
export interface CreateListResponse {
    status_message: string;
    success:        boolean;
    status_code:    number;
    list_id:        number;
}

export class CreateListDto {
    name:        string;
    description: string;
    language:    string;

    constructor(nombre: string, descripcion: string) {
        this.name = nombre;
        this.description = descripcion;
        this.language = 'es';
    }
}

// Generated by https://quicktype.io

export interface AddMovieResponse {
    status_code:    number;
    status_message: string;
}

// Generated by https://quicktype.io

export interface AddMovieDto {
    media_id: number;
}
